apiVersion: v1
kind: Secret
metadata: 
  name: groups-api-secrets
  namespace: backend-api
type: Opaque
data: 
  connection_string: U2VydmVyPW15c3FsLXN2Yy5kYXRhYmFzZXMuc3ZjLmNsdXN0ZXIubG9jYWw7RGF0YWJhc2U9RGlzdHJpYnVpZGVkU3lzdGVtcztVc2VyIElkPXJvb3Q7UGFzc3dvcmQ9anVhbjtTc2xNb2RlPVByZWZlcnJlZDsg
